const CONFIG = {
    introTitle: 'Gửi Thaihoaaa',
    introDesc: `Trái đất vốn lạ thường,
    Mà sao em cứ đi nhầm đường,
    Lạc vào tim anh lẻ loi,
    Đằng sau chữ yêu đây là thương`,
    btnIntro: 'hihi',
    title: 'anh xin lỗi bồ vì nhiều lần đã làm bồ buồn 😥',
    desc: 'Bồ cho anh xin lỗi vì tất cả nhớ 😘 ',
    btnYes: 'Được chứ ',
    btnNo: 'Không, bạn ơi :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Anh yêu em nhiều lắm á em yêu à',
    messDesc: 'Anh sẽ thay đổi dần dần vì em yêu em',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/lemanhtung8302',
}
